php-telegram-bot/core

README.md
src/Command.php
src/Commands/CalcCommand.php
src/Commands/DateCommand.php
src/Commands/HelpCommand.php
src/Commands/LeftChatParticipantCommand.php
src/Commands/NewChatParticipantCommand.php
src/Commands/WeatherCommand.php
src/Commands/WhoamiCommand.php
src/Entities/Entity.php
src/Entities/Message.php
src/Entities/Update.php
src/Telegram.php
structure.sql

The namespace for the external commands wasn't set property. I've just fixed it.

[Fix] Namespace bug for external commands

---

src/Entities/Message.php

I've fixed a little bug. Not all messages to the bot are commands, some of them (messages from the keyboard) can be pure text only.
I've change in the methods getFullCommand and getText to support pure text messagges. 
Hope than travis ci like the code

[Fix] check if is a command before tock

---

src/DB.php

No functional changes, only slight modifications of documentation and code layout.

Initial code cleanup of `DB.php`.

---

src/Admin/ChatsCommand.php
src/Admin/SendtoallCommand.php
src/Admin/SendtochannelCommand.php

No functional changes, only modifications of documentation and code layout.

Initial code cleanup of `Admin commands`.

---

src/Commands/ChannelchatcreatedCommand.php
src/Commands/ChoseninlineresultCommand.php
src/Commands/DateCommand.php
src/Commands/DeletechatphotoCommand.php
src/Commands/EchoCommand.php
src/Commands/GenericCommand.php
src/Commands/GenericmessageCommand.php
src/Commands/GroupchatcreatedCommand.php
src/Commands/HelpCommand.php
src/Commands/InlinequeryCommand.php
src/Commands/LeftchatparticipantCommand.php
src/Commands/NewchatparticipantCommand.php
src/Commands/NewchattitleCommand.php
src/Commands/SlapCommand.php
src/Commands/StartCommand.php
src/Commands/SupergroupchatcreatedCommand.php
src/Commands/WeatherCommand.php
src/Commands/WhoamiCommand.php

This PR is just for filling up the documentation and modifying some code style.
The commands in general need a bigger overhaul to prevent duplicate code and make it more sensible.

Code cleanup for `Commands`

---

README.md
examples/getUpdatesCLI.php
examples/hook.php
examples/set.php
examples/unset.php

Revise README file and correct code snippets.
Prettify example code files.

Correct readme and examples

---

src/Request.php

Hello. I've been reading source code of the library and found a small typo in word Webhook. Thank you for supporting this nice little package.

Fixes typo in word Webhook

---

.travis.yml

Having the database set up is necessary for certain tests which need to be implemented.

Create MySQL database with correct table structure.

---

src/Entities/Document.php
src/Entities/Video.php

Just found those two mistakes.

Fix minor mistakes

---

README.md
src/DB.php
src/Telegram.php

Let you use DB.php with an external pdo connection

Introducing db external connection

---

examples/Commands/HidekeyboardCommand.php

Fix hidekeyboard command

---

src/Entities/ServerResponse.php

Currently executing getMe request returns an exception (it tries to use message object for the returned data).

fix getMe() exception

---

src/Botan.php
src/DB.php
src/Telegram.php
structure.sql

Merging after merging https://github.com/akalongman/php-telegram-bot/pull/198 will most likely make conflict show up in DB.php and structure.sql

Quick updates

---

src/DB.php
structure.sql

instead of inserting whole message into callback query entry reference it in database 
(inserts it to the message table)

Small optimization

---

src/Commands/SystemCommands/InlinequeryCommand.php

inline query command fixed

---

src/Telegram.php
tests/Unit/TelegramTest.php

Add extra methods for enabling admins and adding custom commands paths.
Closes #230

Add flexible methods

---

README.md
examples/getUpdatesCLI.php
examples/hook.php
tests/Unit/TelegramTest.php

Also add an extra test for string numbers.

Update readme and examples for enableAdmin(s)

---

doc/01-utils.md
examples/getUpdatesCLI.php
examples/hook.php

Make sure that logging is set directly after Telegram object initialisation. (thanks @jacklul for pointing this out)
Proofread and update utils.md file.

Update inline comments for hook.php and getUpdatesCLI.php

---

src/Telegram.php

Fix return value for handle() method.

---

src/Entities/InlineKeyboardButton.php
tests/Unit/Entities/InlineKeyboardButtonTest.php

Fix todo of InlineKeyboardButton.
Add tests and update DocBlock.
This PR replaces #257

Improve inline keyboard button

---

composer.json
composer.lock
tests/Bootstrap.php
tests/TelegramBot/Tests/Commands/CommandTest.php
tests/TelegramBot/Tests/Commands/CommandTestCase.php
tests/TelegramBot/Tests/Commands/UserCommands/EchoCommandTest.php
tests/TelegramBot/Tests/Commands/UserCommands/HelpCommandTest.php
tests/TelegramBot/Tests/ConversationTest.php
tests/TelegramBot/Tests/Entities/ChatTest.php
tests/TelegramBot/Tests/Entities/InlineKeyboardButtonTest.php
tests/TelegramBot/Tests/Entities/MessageTest.php
tests/TelegramBot/Tests/Entities/ReplyToMessageTest.php
tests/TelegramBot/Tests/Entities/ServerResponseTest.php
tests/TelegramBot/Tests/Entities/UpdateTest.php
tests/TelegramBot/Tests/TelegramLogTest.php
tests/TelegramBot/Tests/TelegramTest.php
tests/TelegramBot/Tests/TestCase.php
tests/TelegramBot/Tests/TestHelpers.php

Move all tests into a dedicated namespace and folder.

---

src/Entities/Location.php
src/Entities/PhotoSize.php

There were a few blank lines that phpcs hadn't picked up till now.
Have been fixed.

Make phpcs happy again.

---

composer.json

Add dependency for ext-mbstring, as suggested by @IronLady in #92

---

src/Entities/CallbackQuery.php
src/Entities/ChatMember.php
tests/unit/Entities/FileTest.php
tests/unit/Entities/LocationTest.php
tests/unit/Entities/WebhookInfoTest.php

Adds new unit tests
- Entities/WebHookInfo
- Entities/Lacation
- Entities/File

Unit tests

---

src/Commands/AdminCommands/SendtochannelCommand.php
src/Commands/UserCommands/CancelCommand.php
src/Commands/UserCommands/SurveyCommand.php
src/Entities/Keyboard.php
tests/unit/Entities/KeyboardTest.php

hide Keyboard is deprecated since Bot api 2.3
I tested it with my bot

move hideKeyboard to removeKeyboard

---

src/Botan.php

Make Botan integration use monolog debug log + add missing update objects to the tracking
https://github.com/akalongman/php-telegram-bot/issues/341
**Why not error log?**
_Botan API sometimes fails, it would flood the error log!_

Botan integration - quick improvements

---

src/Entities/Entity.php

Properly pass the bot_name to the entity constructor.

---

src/Commands/SystemCommands/ChannelpostCommand.php
src/Commands/SystemCommands/EditedchannelpostCommand.php
src/DB.php
src/Entities/ChannelPost.php
src/Entities/EditedChannelPost.php
src/Entities/Update.php
src/Telegram.php

https://core.telegram.org/bots/api-changelog#november-21-2016
fix https://github.com/akalongman/php-telegram-bot/pull/333#issuecomment-269093857

Add support for channel_post and edited_channel_post

---

examples/Commands/InlinekeyboardCommand.php
src/Entities/InlineKeyboardButton.php
tests/unit/Entities/InlineKeyboardButtonTest.php
tests/unit/Entities/InlineKeyboardTest.php

(Based on 79c58a9bc29b75f5a311f471a61c47c2cdffea67)

Add new switch_inline_query_current_chat option to inline keyboard.

---

examples/Commands/HidekeyboardCommand.php

Thanks @jacklul for spotting this one!

Missed a deprecated hide keyboard method call.

---

src/Botan.php
src/Conversation.php
src/DB.php
src/Entities/Entity.php
src/Entities/Message.php
src/Request.php
src/TelegramLog.php

Fix most of the **Major** scrutinizer issues.

Scrutinizer fixes

---

src/Botan.php

Simplify some code bits.

---

src/Commands/SystemCommands/PinnedmessageCommand.php
src/Telegram.php

Add handler command for pinned_message

---

src/DB.php

Fix param types

---

examples/Commands/ShortenerCommand.php
src/Botan.php
src/Entities/Message.php
src/Telegram.php
src/TelegramLog.php
tests/unit/TelegramLogTest.php

Allow passing of parameters in a sprintf style.
This makes it easier to log messages that contain variables.

Make logger more flexible

---

src/Commands/SystemCommands/ChannelpostCommand.php
src/Commands/SystemCommands/EditedchannelpostCommand.php

_Seems that I've made small mistake, sorry!_

Fix for channel_post and edit_channel_post commands

---

examples/cron.php
src/Telegram.php

So, basically this will let the developers run their commands from crontab easily.
This essentialy is a solution for https://github.com/akalongman/php-telegram-bot/issues/156

Crontab-friendly script

---

src/Commands/AdminCommands/DebugCommand.php
src/Telegram.php
tests/unit/TelegramTest.php

Add a simple debug command that outputs general info about the bot and the server environment.
@jacklul Let me know if there's anything else you'd want in here.
Was thinking of some stats from the DB, but not sure how useful that is for debugging.

Debug command

---

src/ConversationDB.php

Make sure the notes are an array to start with.

---

src/Telegram.php

For the possibility of hierarchical inheritance

Update scope getCommandFromType

---

CHANGELOG.md
README.md
composer.json
examples/Commands/InlinekeyboardCommand.php
examples/Commands/MarkdownCommand.php
examples/Commands/ShortenerCommand.php
src/Request.php
tests/unit/Commands/CommandTest.php
tests/unit/Commands/CommandTestCase.php
tests/unit/ConversationTest.php
tests/unit/Entities/AudioTest.php
tests/unit/Entities/ChatTest.php
tests/unit/Entities/FileTest.php
tests/unit/Entities/InlineKeyboardButtonTest.php
tests/unit/Entities/InlineKeyboardTest.php
tests/unit/Entities/KeyboardButtonTest.php
tests/unit/Entities/KeyboardTest.php
tests/unit/Entities/LocationTest.php
tests/unit/Entities/MessageTest.php
tests/unit/Entities/ReplyToMessageTest.php
tests/unit/Entities/ServerResponseTest.php
tests/unit/Entities/UpdateTest.php
tests/unit/Entities/UserTest.php
tests/unit/Entities/WebhookInfoTest.php
tests/unit/TelegramLogTest.php
tests/unit/TelegramTest.php
tests/unit/TestHelpers.php

@akalongman Scrutinizer auth still needs to be added to the repo, did you get the request email?
[skip ci]

Update organisation links.

---

examples/hook.php

Minor example update with lil note bout $path

[minor] Forgotten $BOT_NAME => $BOT_USERNAME

---

src/Commands/SystemCommands/GenericCommand.php
src/Entities/Entity.php
src/Entities/Update.php

When getting update content, get the Entity object instead of an array.

Fix $update->getUpdateContent() method.

---

examples/Commands/GenericCommand.php
src/Commands/AdminCommands/SendtoallCommand.php

Continuing to take care of the details

Fix some typos

---

CHANGELOG.md
src/DB.php
src/Telegram.php

Version 0.44.1

---

CHANGELOG.md
src/DB.php

Fix #518  - Properly saving Chat IDs

---

CHANGELOG.md
src/Telegram.php

Custom input now also works for getUpdates method.
JSON must be exactly as it gets passed when using getUpdates:
i.e. `{"ok":true,"result":[{"..."}]}`

Add custom_input for getUpdates method.

---

src/DB.php
src/Request.php

fixes https://github.com/php-telegram-bot/core/issues/509#issuecomment-306137865 i guess?

Fix case when handling channel messages (request limiter)

---

CHANGELOG.md
src/Telegram.php

Scheduler patch

---

src/Telegram.php

fix get command from type 'new_chat_members'

---

CHANGELOG.md
README.md

Rewrite parts of the text, code references, examples, links etc.

Update readme to state of 0.46.0

---

CHANGELOG.md
src/Entities/InlineKeyboardButton.php
src/Entities/Payments/Invoice.php
src/Entities/Payments/LabeledPrice.php
src/Entities/Payments/OrderInfo.php
src/Entities/Payments/PreCheckoutQuery.php
src/Entities/Payments/ShippingAddress.php
src/Entities/Payments/ShippingOption.php
src/Entities/Payments/ShippingQuery.php
src/Entities/Payments/SuccessfulPayment.php
src/Entities/Update.php
src/Request.php
tests/unit/Entities/InlineKeyboardButtonTest.php
tests/unit/Entities/InlineKeyboardTest.php

This is the official PR to implement the Bot API 3.0.
For more info on the individual bits, see #501 
~(WIP as it needs to be tested with a client that supports payments)~
Close #501

Bot api 3.0

---

CHANGELOG.md
src/Commands/SystemCommands/ChannelchatcreatedCommand.php
src/Commands/SystemCommands/ChannelpostCommand.php
src/Commands/SystemCommands/DeletechatphotoCommand.php
src/Commands/SystemCommands/EditedchannelpostCommand.php
src/Commands/SystemCommands/GenericCommand.php
src/Commands/SystemCommands/GenericmessageCommand.php
src/Commands/SystemCommands/GroupchatcreatedCommand.php
src/Commands/SystemCommands/LeftchatmemberCommand.php
src/Commands/SystemCommands/MigratefromchatidCommand.php
src/Commands/SystemCommands/MigratetochatidCommand.php
src/Commands/SystemCommands/NewchatmembersCommand.php
src/Commands/SystemCommands/NewchatphotoCommand.php
src/Commands/SystemCommands/NewchattitleCommand.php
src/Commands/SystemCommands/PinnedmessageCommand.php
src/Commands/SystemCommands/SupergroupchatcreatedCommand.php
src/Telegram.php

Just to make the command names work properly using any case, but preferring lower case names.

Command names should be lower case.

---

src/ConversationDB.php

Just like #464 and #520
Fixes #598

Use unique parameters for SQL query

---

CHANGELOG.md
src/DB.php
src/Entities/Chat.php
src/Entities/Message.php
src/Entities/User.php
structure.sql
utils/db-schema-update/0.47.1-unreleased.sql

This PR adds all new features from the Bot API 3.3 update.
Closes #602

Bot API 3.3

---

CHANGELOG.md
src/DB.php

A rather ugly fix for now, hopefully there is a better solution at some point.
Fixes #615

Make sure there are only uniquely named parameters.

---

CHANGELOG.md
src/BotanDB.php
src/ConversationDB.php
src/DB.php

A big cleanup of the DB code, to make it lighter and clearer.
This is NOT a new refactor of the DB system, simply a code cleanup which provides the same functionality as before.

Clean up DB code

---

CHANGELOG.md
README.md

Yay, donations!! (hopefully 😇)

Add donation section to readme.

---

src/Request.php

sendMediaGroup method was missing, see https://core.telegram.org/bots/api#sendmediagroup
ISSUE: https://github.com/php-telegram-bot/core/issues/706

Add new sendMediaGroup method

---

CREDITS

Update contact info

---

src/Telegram.php

 Fix warning when selectTelegramUpdate() returns bool here

---

.travis.yml
CHANGELOG.md
composer.json
composer.lock
src/Telegram.php

Update composer dependencies and fix sniffed code.

Use trusty to enable HHVM and add PHP 7.2 to the mix.

---

README.md

Fix typo and anchor in README.md

Fix typo and anchor

---

CHANGELOG.md
src/Telegram.php

Add defined for not redefine constant BASE_PATH

Prevent redefine constant BASE_PATH

---

CHANGELOG.md
src/Entities/Message.php

Return correct message type

---

CHANGELOG.md
src/Commands/AdminCommands/CleanupCommand.php

Fixes https://github.com/php-telegram-bot/core/issues/946

Fix missing specifier

---

src/Entities/InlineQuery.php

| ?                   |  !
|---                  | ---
| Type             | bug 
| BC Break     |  no
| Fixed issues |

Typo in parameter name

---

.travis.yml

| Type         | bug / feature / improvement
| BC Break     | yes / no
| Fixed issues |

upd 7.4 image

---

src/Telegram.php

| Type         |  improvement
| Fixed issues | #1014

chain the exception throwed when creating command instance

---

CHANGELOG.md
README.md
src/DB.php
src/Entities/KeyboardButton.php
src/Entities/KeyboardButtonPollType.php
src/Entities/MessageEntity.php
src/Entities/Poll.php
src/Entities/PollAnswer.php
src/Entities/Update.php
src/Entities/User.php
src/Request.php
structure.sql
tests/unit/Entities/KeyboardButtonTest.php
utils/db-schema-update/0.61.1-unreleased.sql

| Fixed issues | #1049
Implement Bot API 4.6 that adds the new Polls 2.0 features.

Bot API 4.6

---

CHANGELOG.md
README.md
src/DB.php
src/Entities/BotCommand.php
src/Entities/Dice.php
src/Entities/Message.php
src/Entities/ServerResponse.php
src/Entities/StickerSet.php
src/Request.php
structure.sql
utils/db-schema-update/0.61.1-unreleased.sql

| Fixed issues | #1063 
Add features for Bot API 4.7:
- Dice
- new Sticker Set features
- Bot Commands

Bot API 4.7

---

CHANGELOG.md
README.md
src/DB.php
src/Entities/Dice.php
src/Entities/Poll.php
structure.sql
utils/db-schema-update/0.62.0-unreleased.sql

| Fixed issues | #1081 
Implement Bot API 4.8 with new fields for Poll and Dice entities.

Add new Bot API 4.8 fields to Poll and Dice entities and DB.

---

README.md

Added a new project that's based on this core to the list - no issue to be resolved from this.

Add a new project to the list in README.md

---

CHANGELOG.md
utils/db-schema-update/0.62.0-0.63.0.sql

Fix migration script for older versions of MySQL.

---

src/Exception/InvalidBotTokenException.php

Use single string quotes

---

src/Commands/AdminCommands/DebugCommand.php
src/Commands/Command.php
src/DB.php
src/Entities/ChannelPost.php
src/Entities/EditedChannelPost.php
src/Entities/EditedMessage.php
src/Exception/TelegramException.php
src/Exception/TelegramLogException.php
src/Request.php
src/Telegram.php

Code improvements

---

src/Request.php
src/Telegram.php
src/TelegramLog.php

Code quality fixes

---

CHANGELOG.md
src/Commands/AdminCommands/CleanupCommand.php

| Type         |  improvement
| BC Break     |  no
| Fixed issues | #1138
Wrapped the query a bit for optimization

Speed up clean query

---

CHANGELOG.md
src/Request.php
src/Telegram.php

| Fixed issues | #1165 
- Improve error messages for input retrieval.
- Better Update logging.

Better update logging and error messages.

---

src/Entities/Keyboard.php

| Fixed issues | 1183
Fixed Keyboard and InlineKeyboard constructor without parameters

Fixed keyboard constructur without any parameters

---

src/Entities/Message.php
src/Entities/MessageAutoDeleteTimerChanged.php
src/Entities/VoiceChatEnded.php
src/Entities/VoiceChatParticipantsInvited.php
src/Entities/VoiceChatStarted.php

| Fixed issues | #1186
Added Bot API 5.1 fields and types to the class Message

Added new fields and types to the class Message

---

CHANGELOG.md
README.md
composer.lock
src/DB.php
src/Entities/ChatInviteLink.php
src/Entities/ChatMemberUpdated.php
src/Entities/Message.php
src/Entities/MessageAutoDeleteTimerChanged.php
src/Entities/Update.php
src/Entities/VoiceChatEnded.php
src/Entities/VoiceChatParticipantsInvited.php
src/Entities/VoiceChatStarted.php
src/Request.php
src/Telegram.php
structure.sql
utils/db-schema-update/0.71.0-unreleased.sql

| Type         | feature / improvement
| Fixed issues | #1186
Add all features for Bot API version 5.1 (March 2021)

Bot API 5.1

---

CHANGELOG.md
src/ChatAction.php
src/DB.php
src/Entities/ChatInviteLink.php
src/Entities/ChatJoinRequest.php
src/Entities/Update.php
src/Request.php
structure.sql
utils/db-schema-update/0.74.0-unreleased.sql

Bot API 5.4

---

README.md

Change to correct ImageCommand URL

---

CHANGELOG.md
composer.json
composer.lock

| Fixed issues | #1282 
Allow psr/log version 2 and 3.

Permit version 2 and 3 of psr/log

---

README.md

- added ChessQuizBot to sample projects

Added ChessQuizBot to sample projects

---

src/Request.php

#handle getUpdates on network connection error/disconnected
| Type         | bug 
| Fixed issues | #1432
add guzzle ConnectException

Add catch ConnectionException

---

README.md

| Type         |  improvement
| Fixed issues | 
Added telegram_bot_bundle project (Symfony wrapper) to the list of projects using this library in the README.

Added telegram_bot_bundle project (Symfony wrapper) to the list of projects using this library in the README.
