- src/Commands/CalcCommand.php
- src/Commands/WhoamiCommand.php
Hello! 
I've create two new command for the bot! 
Calc perform simple calcolus
Whoami write you back your username
> Added Calc Whoami Command

- src/Admin/ChatsCommand.php
- src/Admin/SendtoallCommand.php
- src/Admin/SendtochannelCommand.php
- src/Commands/ChannelchatcreatedCommand.php
- src/Commands/ChoseninlineresultCommand.php
- src/Commands/DateCommand.php
- src/Commands/DeletechatphotoCommand.php
- src/Commands/EchoCommand.php
- src/Commands/GenericCommand.php
- src/Commands/GenericmessageCommand.php
- src/Commands/GroupchatcreatedCommand.php
- src/Commands/HelpCommand.php
- src/Commands/InlinequeryCommand.php
- src/Commands/LeftchatparticipantCommand.php
- src/Commands/NewchatparticipantCommand.php
- src/Commands/NewchattitleCommand.php
- src/Commands/SlapCommand.php
- src/Commands/StartCommand.php
- src/Commands/SupergroupchatcreatedCommand.php
- src/Commands/WeatherCommand.php
- src/Commands/WhoamiCommand.php
Changes include:
- Removed the definitions of member variables that had the same values as their inherited defaults. These can be removed since the default values apply anyway.
- Removed superfluous code form execute command.
Fixed #86 in the process
> Remove any unnecessary code from commands.

- src/Admin/ChatsCommand.php
- src/Admin/SendtoallCommand.php
- src/Admin/SendtochannelCommand.php
- src/Commands/ChannelchatcreatedCommand.php
- src/Commands/ChoseninlineresultCommand.php
- src/Commands/DateCommand.php
- src/Commands/DeletechatphotoCommand.php
- src/Commands/EchoCommand.php
- src/Commands/GenericCommand.php
- src/Commands/GenericmessageCommand.php
- src/Commands/GroupchatcreatedCommand.php
- src/Commands/HelpCommand.php
- src/Commands/InlinequeryCommand.php
- src/Commands/LeftchatparticipantCommand.php
- src/Commands/NewchatparticipantCommand.php
- src/Commands/NewchattitleCommand.php
- src/Commands/SlapCommand.php
- src/Commands/StartCommand.php
- src/Commands/SupergroupchatcreatedCommand.php
- src/Commands/WeatherCommand.php
- src/Commands/WhoamiCommand.php
Instead of having to write the same docblocks over and over again for each command, just inherit them for the parent class!
Unfortunately, when generating the documentation, phpdoc gives a notice about not finding the documentation for the member variables, because at compilation time it's impossible to know if it can inherit the values.
That put aside, it's just SO much easier to read the code without tons of comments everywhere.
> Just inherit repeating documentation blocks

- src/DB.php
Fetched fix from @excody .
Now newchat participant and left one are stored propely
> Excody fix

- src/Commands/SystemCommand.php
- src/Request.php
Added the method emptyResponse to use in command that don't need to fire a Request to telegram.
> Empty response

- structure.sql
Fix this issue in table schema
https://github.com/akalongman/php-telegram-bot/issues/114
> Structure.sql

- src/Commands/SystemCommands/NewchatphotoCommand.php
- src/Entities/Message.php
- src/Telegram.php
Noticed this hasn't been added yet, I know this can be handled by genericmessage but having comands for each message type might be a good idea.
> Add new_chat_photo command

- README.md
- src/Exception/TelegramException.php
- src/Logger.php
I introduced the logger Class https://github.com/akalongman/php-telegram-bot/issues/106 to Handle the path of the exception logs.
Don't want to rewrite log system now just path this bug https://github.com/akalongman/php-telegram-bot/issues/96 .
Exception are not stored by default, you can start log then adding:
```
Longman\TelegramBot\Logger::initialize('Exceptionlog.log');
```
in your webhook.php or in your getUpdates.php
> fix Exception Log

- src/Commands/SystemCommands/MigratefromchatidCommand.php
- src/Commands/SystemCommands/MigratetochatidCommand.php
- src/Commands/SystemCommands/SupergroupchatcreatedCommand.php
- src/DB.php
- src/Entities/Message.php
- src/Telegram.php
Code in **SupergroupchatcreatedCommand.php** will never run as intended, **supergroup_chat_created** works just like **group_chat_created**, **migrate_to_chat_id** and **migrate_from_chat_id** are sent seperately.
Placing code from **SupergroupchatcreatedCommand.php** into **MigratetochatidCommand.php** and editing it a bit will also don't work, bot can't message new group id answering to update from old group id. (tried to figure it out and it just doesn't work)
Also **migrate_from_chat_id** is not always sent to bot.
> Add migrate_to_chat_id and migrate_from_chat_id commands

- src/Commands/AdminCommands/ChatsCommand.php
List of changes done:
-all chats are no longer printed by default
-added search by group/user name and also user's first/last name
-chat id will be also shown
-fixed an issue where super groups were listed as normal groups
Showing all chats by default isn't good idea considering someone can have like ~1000 entries in DB, it will take some time and can prevent bot from answering to requests from other people, not to mention the message spam in the conversation.
> Improved 'chats' command

- src/Commands/AdminCommands/ChatsCommand.php
- src/Commands/AdminCommands/WhoisCommand.php
- src/Commands/SystemCommands/GenericCommand.php
- src/DB.php
> Add /whois command

- src/Commands/UserCommands/SurveyCommand.php
Add Location button in a custom keyboard so the user can finish the survey example.
Create an additional state where the bot asks the phone number with 'request_contact' button.
Store the user's picture id and user's phone number in the conversation notes.
> Add location and contact buttons to the Survey example

- src/TelegramLog.php
By default, Monolog removes all line breaks, resulting in a log file that has really long lines.
For debug purposes, it's very difficult to find the relevant info in a long line.
This PR enables line breaks in debug and error logs.
> Add inline line breaks in logs.

- src/Telegram.php
Make sure that a valid database connection exists when using `getUpdates()`.
This doesn't solve the loop problem, but it prevents loop messages from being sent.
Fixes #127
> Using getUpdates needs a valid database connection.

- src/Commands/UserCommands/CancelCommand.php
Message mustn't have an empty text, otherwise Telegram API is sad 😢 
So just output a simple message instead, since there is nothing to cancel if there is no database connection, as no conversation can be active anyway.
> Fix cancel command if no database is connected.

- src/Entities/Message.php
`getText()` method now correctly returns the text, with and without command.
Thanks @commfort for finding this!
Fixes #196
> Correct the getText() method of the Message entity

- src/Request.php
The problem is that there is an invalid argument for Guzzle's `post` method. Bot can't upload files to users using `form_params`, so this fix makes bot to use `multipart` key.
> Fixes issue with file uploading

- src/Commands/SystemCommands/InlinequeryCommand.php
Prevent an error exception when an empty inline query is being handled.
> Return an empty response when an empty inline query is passed.

- phpunit.xml.dist
- structure.sql
- tests/TestHelpers.php
- tests/Unit/Commands/CommandTest.php
- tests/Unit/Commands/CommandTestCase.php
- tests/Unit/Commands/UserCommands/EchoCommandTest.php
- tests/Unit/Commands/UserCommands/HelpCommandTest.php
- tests/Unit/ConversationTest.php
- tests/Unit/Entities/ChatTest.php
- tests/Unit/Entities/MessageTest.php
- tests/Unit/Entities/ReplyToMessageTest.php
- tests/Unit/Entities/ServerResponseTest.php
- tests/Unit/Entities/UpdateTest.php
- tests/Unit/TelegramLogTest.php
- tests/Unit/TelegramTest.php
- tests/Unit/TestCase.php
This PR now allows for local database tests to be configurable. Check the new constants in `phpunit.xml.dist`. Just copy it to `phpunit.xml` and adjust values to your local test environment.
A bunch of DocBlock fixes and test renames.
Also makes more use of TestHelpers class to facilitate entity testing.
> Improve test code

- tests/Unit/Commands/CommandTest.php
Check for the number of failed attempts instead of the content of the exception message, as the message can be quite different between PHP versions and HHVM.
> Improve command constructor test

- src/Entities/ServerResponse.php
- src/Entities/WebhookInfo.php
- src/Request.php
https://core.telegram.org/bots/api#getwebhookinfo
> implement getWebhookInfo method

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Turn quotes into hidden HTML tags to prevent them from being posted by mistake.
> Fix GitHub templates to prevent mistakes

- README.md
- examples/set.php
- examples/unset.php
- src/Entities/WebhookInfo.php
- src/Request.php
- src/Telegram.php
- tests/unit/Entities/WebhookInfoTest.php
Update setWebhook to allow passing of new arguments.
**This change breaks backwards compatibility!**
Fix #345
> Update webhookinfo entity with the latest additions by Telegram.

- examples/unset.php
- src/Request.php
- src/Telegram.php
Fix some error outputs.
For the moment, this PR keeps the `unsetWebhook` method in place for backwards compatibility.
> Use new deleteWebhook method to delete a webhook.

- src/Request.php
Guzzle uses a multipart stream, which doesn't allow arrays, so they need to be encoded to JSON first.
Props @jacklul
> Fix self-signed certificate usage

- examples/Commands/EditmessageCommand.php
- examples/Commands/ShortenerCommand.php
- examples/getUpdatesCLI.php
- examples/hook.php
- src/Botan.php
- src/BotanDB.php
- src/Commands/AdminCommands/SendtochannelCommand.php
- src/Commands/UserCommands/WeatherCommand.php
- src/DB.php
- src/Entities/Keyboard.php
- src/Entities/ServerResponse.php
- src/Request.php
- src/Telegram.php
Botan.io:
- moved to Guzzle
- user can set own timeout for Botan requests `$telegram->enableBotan('TOKEN', ['timeout' => 5])`, defaults to 3
- added shortener usage example
- stated potential usage for `public static $command` in docblock
- fixed botan not working with getUpdates
Other:
- Fixed `Call to a member function getBody() on null` happening on empty or no replies (currently visible on Windows, will be replaced with 'invalid response' exception which is better)
- Fixed code with PHP Code Beautifier and Fixer
- Added example usage of editMessageText 
(I think it would be a good idea to make more usage/command examples based on past closed issues)
> Botan improvements and misc fixes

- src/Commands/SystemCommands/CallbackqueryCommand.php
- src/DB.php
- src/Entities/Chat.php
- src/Entities/InlineQuery/InlineQueryResultAudio.php
- src/Entities/InlineQuery/InlineQueryResultCachedAudio.php
- src/Entities/InlineQuery/InlineQueryResultCachedVoice.php
- src/Entities/InlineQuery/InlineQueryResultVoice.php
- src/Entities/Message.php
- structure.sql
- tests/unit/TestHelpers.php
Added a bunch of changes to reflect the changes of the Telegram API.
- Added the new field forward_from_message_id to Message.
- Added the new parameter cache_time to answerCallbackQuery.
- Added caption fields to sendAudio, sendVoice, InlineQueryResultAudio, InlineQueryResultVoice, InlineQueryResultCachedAudio, and InlineQueryResultCachedVoice.
- New field all_members_are_administrators in the Chat object.
> Implement new api changes

- src/DB.php
- structure.sql
This was missing too!
Now bot can track channel and group public usernames!
> Add 'username' field to 'chat' table

- src/DB.php
Add a new method to the DB class that returns the PDO object for direct querying.
Fix #373
> Make access to the database easier

- examples/cron.php
- examples/getUpdatesCLI.php
- examples/hook.php
- src/DB.php
- src/Request.php
- src/Telegram.php
- structure.sql
#157
So, I've been using this implementation for a while now and I don't see any issues so far, neither any exceptions about Telegram returning response that I've hit the limit.  
By default disabled because it can be heavy on the database. 
Will delay requests using `sleep(1);`.
As mentioned in https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this
- No more than 1 message / second (chat)
- No more than 30 messages / second (globally)
- No more than 20 messages / minute (groups and channels)
This also applies to message editing! Does not apply to methods like getChat or sendChatAction.
Currently I also included 'retry' mode, sometimes if the bot is heavily used 60 seconds wait might not be enough... should I remove this and simply give it only 60 seconds, no …
> Request limiter - prevent hitting Telegram's API limits

- src/TelegramLog.php
- tests/unit/TelegramLogTest.php
Remove error suppression.
Fixes #413
> Fix logger to properly output text that contains '%' symbols.

- src/Entities/Message.php
Small fix of copy/paste mistake. Just set right class (is must be Chat, but it was User) to forward_from_chat field for class Message.
> Fix #421 (Infinity loop after forwarding message from channel)

- src/Commands/Command.php
- src/Commands/UserCommands/HelpCommand.php
- tests/unit/Commands/CommandTest.php
- tests/unit/Commands/CommandTestCase.php
- tests/unit/Commands/CustomTestCommands/HiddenCommand.php
- tests/unit/Commands/CustomTestCommands/VisibleCommand.php
- tests/unit/Commands/UserCommands/HelpCommandTest.php
add `protected $showInHelp` var to `Command.php`
add `public function getShowInHelp()` to `Command.php`
add  `if($command->getShowInHelp()) {}` to wrap single command output at `HelpCommand.php`
with `protected $showInHelp = false;` insert into the command,it is not listed with /help command.
I find this very useful, cause i have some commands i only use over cronjob and don't want this commands to show up at the help command.
> add functionality to allow hiding commands in /help command

- CHANGELOG.md
- examples/getUpdatesCLI.php
- examples/hook.php
- examples/set.php
- examples/unset.php
- src/Entities/Entity.php
- src/Entities/Message.php
- src/Entities/ReplyToMessage.php
- src/Entities/ServerResponse.php
- src/Request.php
- src/Telegram.php
- tests/unit/Commands/CommandTest.php
- tests/unit/Commands/CommandTestCase.php
- tests/unit/ConversationTest.php
- tests/unit/TelegramTest.php
- tests/unit/TestCase.php
Add `getBotId()` method to `Telegram` object.
Regex extracting the id from the API key should be fine.
Rename `bot_name` variables (and similar) into `bot_username` to prevent confusion.
Unit Tests need a fix.
> Misc additions/changes

- examples/cron.php
- examples/getUpdatesCLI.php
- examples/hook.php
- src/DB.php
- src/Request.php
- src/Telegram.php
- Add isRunCommands()
Discussed here https://github.com/php-telegram-bot/core/issues/444
Couldnt find a better name for this function.
- Add optional parameter 'interval' to modify check interval for request limiter
By default there is 1 second delay between a check, which is fine but in some cases developer might want the delay to be slightly smaller (or higher!).
Important Notes:
Settings this to 0.5 will make the check every 0.5 second, this should improve bot resposiveness but can cause a slow down if database server is slow. 
Any value below 1 can cause requests actually reach Telegram API's limits - scenario where previous request was sent just before the next second pops in and another request is instantly served, if this happens too many times in a row Telegram API will issue a …
> Another small additions and changes

- .travis.yml
- CHANGELOG.md
- README.md
- composer.json
- composer.lock
- tests/unit/TestCase.php
This PR ~drops PHP 5.5 but~ adds PHP 7.1 support.
~PHPUnit has been updated to 5.7, as 4.8 isn't supported any more.~
PHPUnit has been updated to the latest possible version depending on the version of PHP.
Webhook added for Travis CI, to get build results in the Support Bot.
Also, I've moved the code check and test scripts to composer, to make it easier to execute them in dev.
> Boost deps

- src/Telegram.php
- tests/unit/TelegramTest.php
Make bot username variable not required (useful for developers using this library only to send requests to Telegram api).
Trying to handle a webhook or getUpdates without bot username will result with exception.
_Wait for merge after merging https://github.com/php-telegram-bot/core/pull/474_
~~@noplanman What do you think about the change I did in https://github.com/php-telegram-bot/core/commit/0ad36434ebfdba0c67a11fdb6f937acdaa16f887#diff-c677a2f49b92b068a764b7b31f669c38R186, it could essentially be useless change but what came to my mind what if `/cmd@`, will this result with `$split_cmd[1]` being empty which would equal empty bot username? I think it should not return true since its '===' check but who knows...~~
> Make bot username variable not required

- CHANGELOG.md
- src/Request.php
All credit for this PR goes to @pavlyuts
Sorry it took so long!
This is basically a copy of #329 and closes #325.
Copying the original PR message here to explain:
---
Makes it possible to send all kind of files from memory, not from file on disk by usage of PSR-7 streams.
All we need is to create PSR-7 stream and pass it as a part of `$data` to any of the `sendXXXX` methods. The patch fixes exec method to handle request as multipart for both cases: file resource and stream.
The key should be set in accordance to the API call type: `document`, `photo`, `audio`, etc. using the corresponding `sendDocument`, `sendPhoto`, `sendAudio`, etc. methods.
PSR-7 metadata `uri` must contain filename.
Code example:
```php
$chat_id = 1234;
$caption = 'File send from memory!';
$stream = …
```
> Send a document as content data using Psr7 stream.

- CHANGELOG.md
- src/Request.php
After setting the `$telegram` object, it is very easy to set a custom Guzzle HTTP Client to allow a custom API URL or simply to modify various parameters (like SSL verification):
```php
Request::setClient(new \GuzzleHttp\Client([
'base_uri' => 'https://149.154.167.197',
'verify'   => false,
]));
```
Fixes #507 
Fixes #511
> Allow setting a custom Guzzle HTTP Client for requests.

- CHANGELOG.md
- src/Commands/AdminCommands/DebugCommand.php
- src/Request.php
- src/Telegram.php
They must now be set manually via `$telegram->setUploadPath(...)` and `$telegram->setDownloadPath(...)`.
Using `Request::downloadFile(...)` without setting the download path now throws an exception!
Close #483
> Up and download folders are undefined by default

- CHANGELOG.md
- src/Commands/AdminCommands/ChatsCommand.php
- src/Commands/AdminCommands/SendtoallCommand.php
- src/Commands/AdminCommands/WhoisCommand.php
- src/DB.php
- src/Request.php
This can be particulary useful now since bots can receive channel messages.
I hope I didn't miss anything, I guess travis will tell...
> Allow selecting channels with selectChats() and sendToActiveChats()

- CHANGELOG.md
- structure.sql
When using a MySQL (or MariaDB) server that does not have `innodb_large_prefix` enabled, indexed columns are limited to 191 characters when using `utf8mb4`.
Thus, when executing the query to create the `user` table, the following error occurs:
```
(HY000/1709): Index column size too large. The maximum column size is 767 bytes.
```
When importing the structure using `mysql` command or phpMyAdmin, all affected columns get set to `COLLATE utf8mb4_unicode_520_ci` on import, which prevents the error from popping up.
Since all columns at the moment are just set to `CHAR(255)`, I think it's better to adjust the column sizes to something more realistic.
For now, the `user.username` column is the only one affected.
Read more about [InnoDB …
> Fix indexed column length and quotes in comments.

- src/Commands/Command.php
- tests/unit/Commands/CommandTest.php
This PR passes all methods called from a Command to the current Update object.
Just like `$this->getMessage()` worked as before, now all other types work too:
*from within a Command's `example()` method*
- `$this->getMessage()`
- `$this->getEditedMessage()`
- `$this->getChannelPost()`
- `$this->getEditedChannelPost()`
- `$this->getInlineQuery()`
- `$this->getChosenInlineResult()`
- `$this->getCallbackQuery()`
> Introduce helper commands for all Update Entity types

- CHANGELOG.md
- src/Commands/SystemCommands/CallbackqueryCommand.php
This allows adding callback hooks to CallbackqueryCommand:
e.g. in `hook.php` when setting up the lib:
```php
CallbackqueryCommand::addCallbackHandler(function (CallbackQuery $query) {
if ($query->getFrom()->getUsername() === 'noplanman') {
// Do something with this callback, but only when requested by @noplanman
}
});
```
Any number of callback handlers can be added like this. All of them get run when a callback is being executed, so each callback function needs to do its own checks to handle the proper calls.
@jacklul I've been thinking of ways to extend this, but I'd like to keep it as simple as possible for now, and I feel this is already quite powerful in itself and allows users to very easily add their own custom code to callbacks. What do you think?
> Callbacks can be added to be executed when callback queries are called.

- CHANGELOG.md
- src/Entities/Chat.php
- src/Entities/ChatMember.php
- src/Entities/ChatPhoto.php
- src/Request.php
- src/Telegram.php
This PR adds all new features from the Bot API 3.1 update.
Refactor `Request` class, removing most custom method implementations.
Note: New fields for [`Chat`](https://core.telegram.org/bots/api#chat) entity have NOT been added to the database structure, as the data can be unreliable, due to only being returned when explicitly requesting it via `getChat`.
> Bot API 3.1

- CHANGELOG.md
- src/Commands/AdminCommands/CleanupCommand.php
This command allows cleaning bot database from old records, goes around constraints by executing queries in specific order.
**NOTE: This command will not cleanup tables created by the developer, only those implemented into the library!** Should this be someway implemented? I guess it could but... records date?
Usage:
- `/cleanup` - will use config (or defaults)
- `/cleanup 30` - passing integer will parse this as '30 days'
- `/cleanup 10 minutes` - this will be parsed just as provided
Config variables:
```php
$telegram->setCommandConfig('cleanup', ['tables_to_clean' => 'message', 'edited_message']);
$telegram->setCommandConfig('cleanup', ['time_to_clean' => ['message' => '7 days', 'edited_message' => '30 days']]);
```
Default values:
```php
'botan_shortener'      => '30 days',
'chat' …
```
> Add 'cleanup' command

- CHANGELOG.md
- src/Commands/Command.php
This feature adds a new parameter to be set for commands, forcing it to be used only in private chats.
If a `private_only` command is used in any public group, a message is sent to the user's private chat to notify that it's not allowed.
> New command parameter to enforce usage in private chats only.

- src/Commands/Command.php
Make sure we only filter update types that directly call a command
Fixes
`Error: Call to a member function getChat() on null in /home/jacklul/domains/jacklul.com/cat/e621searchbot/vendor/longman/telegram-bot/src/Commands/Command.php:372`
error in 0.47.0 when command with `$private_only = true` is called by non-message update type.
> Fix for 0.47.0

- CHANGELOG.md
- src/Entities/ServerResponse.php
Make it work like [`print_r`](https://secure.php.net/manual/en/function.print-r.php) regarding return value.
```php
$response->printError();              // prints error, returns true
$error = $response->printError(true); // returns error
```
Fixes #502
> Correct the printError method

- CHANGELOG.md
- src/Entities/Message.php
`reply_to_chat` and `reply_to_message` fields are not inserted because of this small mistake.
> Fix for #596

- CHANGELOG.md
- src/Request.php
docblock comments for methods used by Payments have been added, as they clearly got forgotten somewhere along the way.
> Correctly add payment methods to Request class.

- CHANGELOG.md
- src/Commands/Command.php
- src/Entities/CallbackQuery.php
- src/Entities/InlineQuery.php
- src/Entities/InlineQuery/InlineQueryResult.php
- src/Entities/InlineQuery/InlineQueryResultArticle.php
- src/Entities/InlineQuery/InlineQueryResultAudio.php
- src/Entities/InlineQuery/InlineQueryResultCachedAudio.php
- src/Entities/InlineQuery/InlineQueryResultCachedDocument.php
- src/Entities/InlineQuery/InlineQueryResultCachedGif.php
- src/Entities/InlineQuery/InlineQueryResultCachedMpeg4Gif.php
- src/Entities/InlineQuery/InlineQueryResultCachedPhoto.php
- src/Entities/InlineQuery/InlineQueryResultCachedSticker.php
- src/Entities/InlineQuery/InlineQueryResultCachedVideo.php
- src/Entities/InlineQuery/InlineQueryResultCachedVoice.php
- src/Entities/InlineQuery/InlineQueryResultContact.php
- src/Entities/InlineQuery/InlineQueryResultDocument.php
- src/Entities/InlineQuery/InlineQueryResultGif.php
- src/Entities/InlineQuery/InlineQueryResultLocation.php
- src/Entities/InlineQuery/InlineQueryResultMpeg4Gif.php
- src/Entities/InlineQuery/InlineQueryResultPhoto.php
- src/Entities/InlineQuery/InlineQueryResultVenue.php
- src/Entities/InlineQuery/InlineQueryResultVideo.php
- src/Entities/InlineQuery/InlineQueryResultVoice.php
- src/Entities/Payments/PreCheckoutQuery.php
- src/Entities/Payments/ShippingQuery.php
...for replying to commands and answering queries.
(*Note:* Relies on #633 that add query answering for Payments.)
This a part of #576 (maybe more will come later).
For now though, simply add helpers to reply to messages and answer the various queries (Callback, Inline, Payments) more directly from inside commands.
```php
$this->replyToChat('My reply text', $data_array_for_any_extras);
```
vs.
```php
$data = [
'chat_id' => $this->getMessage()->getChat()->getId(),
'text'   => 'My reply text',
// any extras, like keyboard, parse mode, etc.
];
Request::sendMessage($data);
```
(This takes `Message`, `EditedMessage`, `ChannelPost` and `EditedChannelPost` into account.)
To answer a query callback:
```php
$callback_query->answer(['text' => 'Settings updated!']);
```
vs.
```php
$data = [ …
```
> Implement some helper methods

- src/Entities/Message.php
- src/Entities/StickerSet.php
Only code clean up for better code quality
> No new feature, No bug fix

- CHANGELOG.md
- src/Entities/Message.php
- src/Telegram.php
Also add missing type checks, removing some unnecessary ones.
@jacklul Just to be safe, `Telegram.php:423` really isn't required, right? It's literally an array of all other types except for `message`, which is checked in the other `if`. There can't be any other value there anyway, right?
> Add missing Payment properties to Message entity

- .scrutinizer.yml
- CHANGELOG.md
- src/DB.php
- src/Entities/Message.php
- src/TelegramLog.php
- tests/unit/Entities/MessageTest.php
Some improvements and fixes found by Scrutinizer, reducing the timeout for external code coverage to speed up manual triggers.
Fix return value of `Message::getCommand()` if message is text only. Now returns `null` instead of `false`.
> Scrutinizer improvements

- CHANGELOG.md
- src/Entities/InlineKeyboardButton.php
> Correctly check for empty value, instead of using empty().

- CHANGELOG.md
- src/Entities/Chat.php
- src/Entities/InlineQuery/InlineQueryResultLocation.php
- src/Entities/InputMessageContent/InputLocationMessageContent.php
- src/Entities/Message.php
- src/Request.php
This implements latest additions for Bot API 3.4.
Closes #674
> Bot api 3.4

- CHANGELOG.md
- src/Entities/InlineKeyboardButton.php
- src/Entities/Payments/PreCheckoutQuery.php
- src/Entities/Payments/ShippingOption.php
- src/Entities/Payments/ShippingQuery.php
Fixes some wrongly linked objects in payment entities.
> Fix payment related entity relations and types.

- CHANGELOG.md
- src/Entities/InlineKeyboardButton.php
- src/Entities/InlineQuery.php
- tests/unit/Entities/InlineKeyboardButtonTest.php
> Allow empty string for `switch_inline_query` parameters

- CHANGELOG.md
- src/DB.php
In cases where there is no date specified in the request, use the current timestamp.
Fixes #737
> Fix empty date for User and Chat entities

- src/DB.php
- src/Telegram.php
This is mainly for getUpdates in a `while (true)` loop, there is also no need to make it an exception.
> Do not process duplicated updates, prevent stopping the script

- composer.json
This shouldn't break anything.
Tested it in Windows command line and linux subsystem.
Currently on windows command line it doesn't seem to execute:
```
>composer check-code
> ./vendor/bin/phpcs --standard=phpcs.xml -snp --encoding=utf-8 src/ tests/ --report-width=150
'.' is not recognized as an internal or external command,
operable program or batch file.
Script ./vendor/bin/phpcs --standard=phpcs.xml -snp --encoding=utf-8 src/ tests/ --report-width=150 handling the check-code event returned with error code 1
```
> Update scripts lines to work on both Unix and Windows

- CHANGELOG.md
- src/DB.php
- src/Entities/InputMedia/InputMediaVideo.php
- src/Entities/Message.php
- structure.sql
- utils/db-schema-update/0.52.0-unreleased.sql
Save connected_website info for login widget.
Add streamable parameter to InputMediaVideo.
Closes #789
> Bot API 3.6

- CHANGELOG.md
- src/Commands/AdminCommands/SendtochannelCommand.php
Update the sending method of `/sendtochannel` to use the magic `Request::__callStatic` method.
Fixes #798
> Fix method call for sending messages with /sendtochannel command.

- CHANGELOG.md
- src/Telegram.php
This needs discussion whenever my approach works correctly in all cases.
Would love if you could test it out guys!
> Allow running getUpdates without database connection

- CHANGELOG.md
- src/Commands/AdminCommands/SendtoallCommand.php
- src/Commands/AdminCommands/SendtochannelCommand.php
Improve and partly rewrite `/sendtochannel` and `/sendtoall` commands.
It would be ideal to use the message composition of `/sendtochannel` in `/sendtoall` as well and then maybe move them both out of core, what do you guys think?
@php-telegram-bot/developers @Hitmare @bafplus
> Improve admin send commands

- src/Entities/ServerResponse.php
- tests/unit/Entities/ServerResponseTest.php
Fixed Request::getStickerSet($data)->getResult() returning a Chat object. It now returns a StickerSet object as intended.
This fixes #836
> Fix getStickerSet (#836)

- src/Exception/InvalidBotTokenException.php
- src/Request.php
https://github.com/php-telegram-bot/core/issues/850
Also added sending raw response body to debug log in case we can't decode the json, should help in troubleshooting.
> Throw unique exception on invalid token

- CHANGELOG.md
- README.md
- src/ChatAction.php
- src/Telegram.php
#858 add chat action constants
> #858 add chat action constants

- CHANGELOG.md
- README.md
- src/DB.php
MySQL credentials array now allows a `port` parameter to be set:
```php
$mysql_credentials = [
'host'     => 'localhost',
'port'     => 3306,        // new optional parameter
'user'     => 'dbuser',
'password' => 'dbpass',
'database' => 'dbname',
];
```
Fixes #857
> Add setting to define custom MySQL port.

- CHANGELOG.md
- README.md
- src/DB.php
- src/Entities/Animation.php
- src/Entities/Audio.php
- src/Entities/Contact.php
- src/Entities/InlineQuery/InlineQueryResultContact.php
- src/Entities/InlineQuery/InlineQueryResultVenue.php
- src/Entities/InputMedia/InputMediaAnimation.php
- src/Entities/InputMedia/InputMediaAudio.php
- src/Entities/InputMedia/InputMediaDocument.php
- src/Entities/InputMedia/InputMediaVideo.php
- src/Entities/InputMessageContent/InputContactMessageContent.php
- src/Entities/InputMessageContent/InputVenueMessageContent.php
- src/Entities/Message.php
- src/Entities/MessageEntity.php
- src/Entities/Venue.php
- src/Request.php
- structure.sql
- utils/db-schema-update/0.54.0-unreleased.sql
This PR adds all changes from Bot API 4.0, except the Telegram Passport things, which will be done as a separate PR.
Part of #869
> Bot API 4.0 - NO Telegram Passport

- CHANGELOG.md
- src/Request.php
This fixes #897 and #666 more properly.
This PR is intended as a hotfix for version 0.54.1
> Fix sendToActiveChats

- CHANGELOG.md
- src/Entities/CallbackQuery.php
- src/Request.php
Add `Request::editMessageMedia()` and `CallbackQuery::getChatInstance()`
Fixes #915
> Add 2 missing methods

- CHANGELOG.md
- src/Botan.php
- src/BotanDB.php
- src/Telegram.php
https://github.com/php-telegram-bot/core/issues/924
Remove it after some time
> Deprecate Botan.io integration

- CHANGELOG.md
- src/Commands/AdminCommands/CleanupCommand.php
This should prevent constrain errors, one of side effects observed is that some messages might not get deleted in the first run. #917
Usage of two additional nested subqueries is extremely heavy here though... not sure if doing one select query and then using PHP to select ids to remove wouldn't be a lighter solution here.
PS. telegram_update query was broken because of this missing `AND updated_at < \'%1$s\'` statement for `chat` table - it didn't clean the table until I added that - @noplanman ?
> Possible fix for #917

- CHANGELOG.md
- src/Entities/Entity.php
- src/Entities/ServerResponse.php
- src/Request.php
- tests/unit/Entities/ServerResponseTest.php
Neat little internal helper to simplify the passing of files to media related methods.
Basically, it automatically generated multipart fields with the attached files and links them automagically.
~~*todo*: Same procedure for `thumb` fields.~~
```php
Request::sendMediaGroup([
'chat_id'  => $chat_id,
'media'    => [
new InputMediaPhoto(['media' => '/path/to/some/photo.png']), // direct path as string is now possible too!
new InputMediaVideo(['media' => Request::encodeFile('/path/to/my/video.mp4'))]),
new InputMediaPhoto(['media' => Request::encodeFile('/path/to/another/photo.png']),
],
]);
```
instead of
```php
Request::sendMediaGroup([
'chat_id'  => $chat_id,
'photo_1'  => Request::encodeFile('/path/to/some/photo.png'),
'photo_2'  => Request::encodeFile('/path/to/another/photo.png'), …
```
> Helper for sending `InputMedia` objects

- CHANGELOG.md
- composer.json
- composer.lock
- src/DB.php
- src/TelegramLog.php
In preparation for 0.56.0 release...
> Upgrade dependencies fix PHPCS

- CHANGELOG.md
- src/DB.php
- src/Entities/ChatMember.php
- src/Entities/Message.php
- src/Entities/Poll.php
- src/Entities/PollOption.php
- src/Entities/Update.php
- src/Request.php
- structure.sql
- utils/db-schema-update/unreleased.sql
This PR adds all changes from Bot API 4.2.
@php-telegram-bot/developers 
Still WIP because the way update requests are saved needs to be extended to `shipping_query` and `pre_checkout_query` as well, which are part of #885 
I think we can get this merged and I'll fix up the other missing things in the separate PR. Also needs to be optimised, as the way the `telegram_update` table is being populated is pretty ugly at the moment :confounded: 
Closes #944
> API 4.2 - Polls

- CHANGELOG.md
- src/DB.php
> Save forward_date correctly to the DB.

- CHANGELOG.md
- src/Entities/InputMedia/InputMedia.php
| Fixed issues | #934 
Abstract `InputMedia` methods weren't being satisfied with annotated class methods.
> InputMedia methods fixed

- CHANGELOG.md
- README.md
- SECURITY.md
Update and improve the readme and extend the changelog to make it more useful for external integrations, like Tidelift and GitHub releases.
> Update README and CHANGELOG

- CHANGELOG.md
- src/TelegramLog.php
- tests/unit/TelegramLogTest.php
| Fixed issues | #982 
- Don't output deprecation error if no logging is enabled.
- Allow more logging flexibility.
> Fix logging deprecation output

- CHANGELOG.md
- src/Request.php
| Fixed issues | #985 
Custom HTTP Client is used if it has already been set before Telegram initialisation.
> Use existing HTTP client on Telegram initialisation

- CHANGELOG.md
- src/Telegram.php
When a command that doesn't exist is executed, the `GenericCommand` should be executed instead, not `GenericmessageCommand`.
> Non-existing commands should execute `GenericCommand`.

- CHANGELOG.md
- src/DB.php
| Fixed issues | #995
The boolean value for the Polls `is_closed` field now gets saved correctly.
> Save boolean value for Polls correctly in DB.

- CHANGELOG.md
- README.md
- composer.json
- composer.lock
- src/Commands/Command.php
- src/Commands/SystemCommands/CallbackqueryCommand.php
- src/Commands/SystemCommands/InlinequeryCommand.php
- src/Entities/InlineQuery.php
- src/Entities/Update.php
- src/Telegram.php
| Fixed issues | none
- Fix some links in the readme.
- Correct some docblocks.
- Use internal helper methods (like `replyToChat()` and `answer()`).
- Correctly use `Request::answerInlineQuery` in `InlineQuery::answer`.
- Smaller code simplifications.
> Small code fixes and simplifications

- .travis.yml
- CHANGELOG.md
- utils/db-schema-update/0.60.0-0.61.0.sql
| Type         | bc fix
| Fixed issues | #1023 
Fix broken DB schema update script and add tests to safeguard from future mistakes like this :+1:
> Fix DB schema update script and add tests for them.

- CHANGELOG.md
- src/Entities/Animation.php
- src/Entities/Message.php
| Fixed issues | #1042
Returns `animation` message type for GIF message instead of `document`.
> Return correct type for GIF message.

- src/Conversation.php
> Allow to store in notes unicode, like cyrillic

- CHANGELOG.md
- src/Request.php
| Fixed issues | #1047
Also perform an `attach://` local media inclusion for `thumb` parameter in InputMedia requests.
> Include "thumb" property in inputMediaHelper

- CHANGELOG.md
- src/DB.php
- src/Entities/Chat.php
- src/Entities/KeyboardButton.php
- src/Entities/Message.php
- src/Request.php
- Remove unnecessary `entityof` checks.
- Remove unused `Request::$input` variable.
- Fixed various docblock annotations.
- Allow setting request client to be of type `ClientInterface` (instead of the concrete `Client` object)
> Scrutinizer fixes

- CHANGELOG.md
- src/Commands/SystemCommands/GenericmessageCommand.php
- src/Telegram.php
This is a trivial change so I decided not to make an issue for it.
This PR replaces occurrences of 'generic' and 'genericmessage' with class constants to improve code clarity and prevent typos. Having class constants with proper comments also helps understand the expected behaviour.
> Use class constants instead of strings for 'generic' and 'genericmessage'

- CHANGELOG.md
- structure.sql
- utils/db-schema-update/0.62.0-unreleased.sql
| Fixed issues | #1086 
Add the missing `user_id` field to the primary key of the `poll_answer` database table.
> Add `user_id` to the primary key of the `poll_answer` table

- CHANGELOG.md
- phpunit.xml.dist
- tests/unit/ConversationTest.php
- tests/unit/TestHelpers.php
| Fixed issues | -
Allow setting the MySQL port for the testsuite, to make local testing more flexible.
> Allow custom MySQL port to be defined for tests.

- CHANGELOG.md
- src/Entities/Entity.php
- tests/unit/Entities/EntityTest.php
- tests/unit/Entities/UserTest.php
| Fixed issues | #1093 
- Add new static method `Entity::parseMarkdownV2` to handle MarkdownV2.
- Change `Entity::parseMarkdown` method to be static, thus not requiring an explicit object.
> Add static method `Entity::parseMarkdownV2` to handle MarkdownV2.

- CHANGELOG.md
- doc/01-utils.md
- src/TelegramLog.php
This will remove bot token from debug http log streams, specifically from the URL path, I don't think there is any other place the token shows up?
So this:
```
> POST /bot123456789:AAHc2FVEadqyhkTYcUuG1RiYR4Hfgpwc/sendMessage HTTP/1.1
```
becomes this:
```
> POST /botBOT_TOKEN_REMOVED/sendMessage HTTP/1.1
```
Can be disabled on demand with `TelegramLog::$remove_bot_token = false`.
Having it enabled as default will make it safe for the people to post these logs for troubleshooting.
Regex is literally modified one from `Telegram.php:172`.
My original idea was to cache the token in the class to not run regex for each entry but people might be running some weird setups where they handle multiple bots in single script.
> Remove bot token from debug stream

- CHANGELOG.md
- doc/01-utils.md
- src/Request.php
- src/TelegramLog.php
| Fixed issues | #1088 
Add a new `TelegramLog::$always_log_request_and_response` variable, to output request data to the debug log before posting the request itself to Telegram.
> Allow logging request data in the debug log

- CHANGELOG.md
- structure.sql
- utils/db-schema-update/0.60.0-0.61.0.sql
- utils/db-schema-update/0.62.0-unreleased.sql
Remove duplicate foreign key and fix broken KEY update.
> MySQL fixes

- CHANGELOG.md
- README.md
- src/DB.php
- src/Entities/Message.php
- structure.sql
- utils/db-schema-update/0.62.0-unreleased.sql
| Fixed issues | #1106 
Add new `via_bot` field to implement Bot API 4.9.
@php-telegram-bot/developers I've not been able to reproduce a situation that actually gives me that field in an update. Do any of you know how a message needs to be sent to have it populated?
> Add via_bot field for Bot API 4.9

- CHANGELOG.md
- src/Telegram.php
Fixes regex and `runCommands()`
Closes #1114
> Custom namespace fixes

- composer.json
- composer.lock
| Fixed issues | #1127 
Add support for Guzzle HTTP version 7.x. This change allows to use php-telegram-bot with Laravel 8.x apps. Not breaking backwards compatibility here, because project works both with 6.x and 7.x Guzzle versions.
An improvement over #1130, which was backwards incompatible.
> feat: upgrade guzzlehttp/guzzle to 7.x

- CHANGELOG.md
- src/Telegram.php
- tests/Unit/TelegramTest.php
Define empty path for download and upload path variables, to prevent `must be of the type string, null returned` error
> Fix path assignment for download and upload paths

- CHANGELOG.md
- src/Request.php
| Fixed issues | #923 #1062
When sending long messages with `Request::sendMessage(...)` all response objects are now returned in an extra parameter which is passed by reference:
```
Request::sendMessage($data, $extras);
// `$extras['responses']` lists all `ServerRequest` response objects for split message sending
```
@Abduvokhid I know it's been a long time, but what do you think of this solution?
@jacklul Would appreciate any feedback on this, thanks 🙏
> Return all sendMessage response objects in referenced array variable

- CHANGELOG.md
- src/Telegram.php
Fix for `getUpdates` method, when no explicit limit is defined. It seems the Bot API return value when passing `0` as the limit has changed. Before it would send 100 updates, now it sends just 1. By changing the value to `null`, the parameter is actively ignored, applying the default of 100.
> Fix getUpdates method to retrieve all updates when no limit is set.

- CHANGELOG.md
- README.md
- src/Request.php
| Fixed issues | #1161 
Add a new method `Longman\TelegramBot\Request::setCustomBotApiUri()` to define a custom Bot API and file download URI, which is used for handling updates and in `Request::downloadFile()`.
> Allow custom Bot API server to be used

- CHANGELOG.md
- src/Telegram.php
| Fixed issues | #1180
Make sure the command text is properly passed via the Update object when running commands via `Telegram::runCommands`.
> Pass correct message text to commands run via Telegram::runCommands

- CHANGELOG.md
- src/DB.php
| Fixed issues | #1176  
The request limiter counter now accepts both integer and string values as the chat ID.
> Accept chat ID as integer and string for request limiter counter

- src/Entities/ChatMember.php
| Fixed issues | #1186
Added Bot API 5.1 fields to class ChatMember
> Added new fields to class ChatMember

- CHANGELOG.md
- structure.sql
- utils/db-schema-update/0.71.0-unreleased.sql
| Fixed issues | #1185
Fix type of `message.edit_date` field and set it to `timestamp`
> Fix message.edit_date type as timestamp.

- utils/db-schema-update/0.71.0-unreleased.sql
| Fixed issues | #1186 
Schema migration
> Schema migration

- src/Entities/ChatInviteLink.php
- src/Entities/ChatMemberUpdated.php
- src/Entities/Update.php
| Fixed issues | #1186 
As a starting point.
> Added updates about member status changes in chats

- CHANGELOG.md
- README.md
- src/Entities/Update.php
- src/Telegram.php
| Fixed issues | #1201 
Add an extra parameter to `Telegram::handleGetUpdates` to define allowed types. If no update types are passed, allow ALL update types, to make sure that special ones like `chat_member` (which MUST be defined to receive) also get fetched.
> Allow defining update types when handling updates via `getUpdates` method

- src/Telegram.php
- tests/Unit/TelegramTest.php
| Type         | bug + feature
| Fixed issues | 1205
Add support to include commands classes via PSR4, and old method (pathes) works too.
Fix regex for search 'namespace' 
Add tests.
> PSR4 command classes include

- CHANGELOG.md
- README.md
- src/Commands/Command.php
- src/Telegram.php
- tests/Unit/Commands/CustomTestCommands/DummyAdminCommand.php
- tests/Unit/Commands/CustomTestCommands/DummySystemCommand.php
- tests/Unit/Commands/CustomTestCommands/DummyUserCommand.php
- tests/Unit/TelegramTest.php
| Fixed issues | #1205
Improve the implementation of adding command classes directly to the bot.
Add changelog entry and update readme.
> Improve PSR4 command classes

- CHANGELOG.md
- README.md
- src/ChatAction.php
- src/DB.php
- src/Entities/InlineQuery.php
- src/Entities/InputMessageContent/InputInvoiceMessageContent.php
- src/Entities/Message.php
- src/Entities/VoiceChatScheduled.php
- structure.sql
- utils/db-schema-update/0.72.0-unreleased.sql
| Fixed issues | #1215 
Implement Bot API 5.2
> Add Bot API 5.2, Payments 2.0 and various fixes

- src/DB.php
| BC Break     | no 
| Fixed issues | #1219
There is a new option for MySQL credentials options to connect to MySQL db with using unix socket connection.
> Possibility to connect to MySQL db with using unix socket connection

- CHANGELOG.md
- src/Telegram.php
Fix running custom commands via `Telegram::runCommands`.
Fixes #1214
e.g.
```php
// ParentCommand.php
public function execute(): ServerResponse
{
$responses = $this->getTelegram()->runCommands(['/child with params']);
// Do other stuff...
return Request::emptyResponse();
}
```
```php
// ChildCommand.php
public function execute(): ServerResponse
{
// Do more stuff here...
return Request::emptyResponse();
}
```
> Fix Telegram::runCommands for User and nested calls

- src/Request.php
- src/Telegram.php
As described in #1225 the `setWebhook` method filters the data array for allowed options, but doesn't allow `drop_pending_updates`. This PR fixes this.
> Fixed non-working drop_pending_updates in setWebhook and deleteWebhook

- src/Entities/Message.php
At php 8.1 got some deprecations:
```
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /srv/app/vendor/longman/telegram-bot/src/Entities/Message.php on line 161
Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/app/vendor/longman/telegram-bot/src/Entities/Message.php on line 264
```
Fix ensures that passed parameter is a string.
> PHP 8.1 deprecations fix

- src/Telegram.php
Solve the problem that the default command cannot be removed
| Type         | feature 
| Fixed issues | Solve the problem that the default command cannot be removed
> feat: add resetCommandsPaths

- CHANGELOG.md
- README.md
- composer.lock
- src/Entities/MessageEntity.php
Only a type-hint update appearently.
> Bot API 5.6

- src/Entities/Entity.php
- tests/Unit/Entities/KeyboardTest.php
> Fixes issue #1303

- src/Telegram.php
https://core.telegram.org/bots/api#setwebhook
```
A secret token to be sent in a header “X-Telegram-Bot-Api-Secret-Token” in every webhook request, 1-256 characters. Only characters A-Z, a-z, 0-9, _ and - are allowed. The header is useful to ensure that the request comes from a webhook set by you.
```
| Fixed issues |
> add secret_token

- src/Entities/Chat.php
- src/Entities/Sticker.php
- src/Entities/User.php
- src/Request.php
- src/Telegram.php
| Fixed issues | #1331 
Bot API v6.1
> Bot API 6.1

- CHANGELOG.md
- src/DB.php
- structure.sql
- utils/db-schema-update/0.77.1-unreleased.sql
| Fixed issues | #1331 
Add new fields to DB schema
> Add DB changes for Bot API 6.1

- src/Telegram.php
| BC Break     | no 
| Fixed issues | 
If I handle updates the following way:
```
$tg = new Telegram('token', 'username');
$tg->useGetUpdatesWithoutDatabase();
$tg->handleGetUpdates();
$lastUpdateId = $tg->getLastUpdateId();
```
And there are no updates, then I get the following error:
Longman\TelegramBot\Telegram::getLastUpdateId(): Return value must be of type int, null returned
Actually, _null_ is a fine result in this case, so I suppose that getLastUpdateId() could be able to return _null_.
> Nullable return type for the getLastUpdateId() method

- src/Entities/Chat.php
- src/Entities/MessageEntity.php
- src/Entities/Sticker.php
- src/Entities/StickerSet.php
- src/Request.php
| Fixed issues | 
upgrade code to bot api v6.2
> Bot API 6.2

- src/Entities/ChatInviteLink.php
Fixes a method name typo in ChatInviteLink's PHPDoc.
> Fix typo in method name.

- src/Telegram.php
- tests/Unit/Commands/CustomTestCommands/DummyAdminCommand.php
- tests/Unit/Commands/CustomTestCommands/DummySystemCommand.php
- tests/Unit/Commands/CustomTestCommands/DummyUserCommand.php
- tests/Unit/TelegramTest.php
| Fixed issues | #1364
As explained in #1364, it's currently impossible to define commands containing underscores.
This PR enables it.
For example:
- a `FoobarCommand` class defines the `/foobar` command
- a `FooBarCommand` class defines the `/foo_bar` command (this is a BC break)
PS: closes #1364
> Enable using commands containing underscores

- src/Entities/Message.php
dice
forum_topic_created
forum_topic_closed
forum_topic_reopened
| Fixed issues | #1371
These are message types, i found it added to Message::subEntities but not added to Message::getType.
I cannot confirm if there are more things forgotten.
I think it should be added, but i cannot confirm too.
If should not be added, please tell why.
> Message::getType lost some value

- src/Entities/Entity.php
Add `AllowDynamicProperties` attribute to Entities.php for PHP8.2 compatibility. Not a permanent/final solution, but good enough to allow upgrades.
#1375
> Feat: allow dynamic properties for PHP8.2

- src/Telegram.php
| Type         | bug 
| Fixed issues | #1383
> Fix issue #1383 with no updates for CustomCommand

- src/Entities/Entity.php
- tests/Unit/Entities/EntityTest.php
Introduce usage of magic __set and __get methods to handle dynamic properties in Entities class.
#1375
> Refactor: better handling of dynamic properties for Entities

- src/Entities/Entity.php
- src/Exception/UndefinedPropertyException.php
Renamed `$parameters` to `$fields`,
added new `UndefinedPropertyException` when trying to access non-defined properties on Entity,
Fixed toJson methods.
> Refactoring after new handling of dynamic properties on Entity

- src/Entities/Entity.php
- src/Entities/ServerResponse.php
- src/Exception/UndefinedPropertyException.php
Better handling of the `raw_data` property, moving it to a dedicated property instead of sharing the main data array.
> Handle raw_data better in Entity class

- CHANGELOG.md
- src/DB.php
- src/Entities/Chat.php
- src/Entities/Message.php
- src/Entities/PollAnswer.php
- src/Entities/Story.php
- src/Request.php
- structure.sql
- utils/db-schema-update/0.81.0-unreleased.sql
| Type         | feature / improvement
| Fixed issues | #1417 
Implement Bot API 6.8
> Bot API 6.8

- src/Telegram.php
| Fixed issues | 
This fix the following TypeError:
Exception::__construct():
Argument #2 ($code) must be of type int, Exception given
> Fix building TelegramException in getCommandsList()

- CHANGELOG.md
- src/Entities/ChatAdministratorRights.php
- src/Entities/ChatMember/ChatMemberAdministrator.php
- src/Entities/WriteAccessAllowed.php
| Fixed issues | #1426 
Bot API 6.9
> Bot API 6.9

- src/Commands/AdminCommands/ChatsCommand.php
- src/Commands/AdminCommands/CleanupCommand.php
- src/Commands/AdminCommands/DebugCommand.php
- src/Commands/AdminCommands/SendtochannelCommand.php
- src/Commands/AdminCommands/WhoisCommand.php
- src/Commands/Command.php
- src/Commands/SystemCommand.php
- src/Commands/UserCommands/StartCommand.php
| Fixed issues | #1456
in some case maybe users want to edit command and when the commend edited the `$this->getMessage()` return null and must use `$this->getEditedMessage()` to fix this issue
> Fix PHP Error - Call to a member function getChat() on null
